### ISSUE TITLE
Add python3.6 build

### ISSUE THREAD

**Issue by bsipocz** [conda-forge/glueviz-feedstock#17]
I'm adding python3.6 packages to the astropy channel and since we copy over the rest of the glue packages from here it would be brilliant to add that to the matrix once it works.

(It seems to have some compatibility issues, that I haven't seen for any of the other packages https://travis-ci.org/bsipocz/glueviz-feedstock/jobs/190309794)

**Comment by astrofrog** [comment]
@bsipocz - some of the dependencies for glue don't exist yet (for 3.6) but I'm working on it :)

**Comment by astrofrog** [comment]
@bsipocz - I forgot to close this, but this has been done for a while

**Comment by bsipocz** [comment]
No worries, I should also make it a habit to go through the issues I opened in various places and close them. Let alone the PRs :)
